### ISSUE TITLE
Loses location if app is switched out of

### ISSUE THREAD

**Issue by PuterPro** [kaangiray26/geddit-app#10]
First off, FABULOUS app!! I'm very very impressed.
But... 
If you accidentally double tap back button or otherwise switch out of the app, when you switch back, it loses your progress and reloads like it just launched.
I'd love to see it keep my place instead of making me scroll for 5 mins on a single accidental button push.
;)
Cheers and well done.

**Comment by kaangiray26** [comment]
Thanks for the kind words!

I've pushed some updates. Now it requires you to press the back button two times in a row to exit the app. If you don't press the back button twice, the timer will reset the button state after 2 seconds of inactivity.

**Comment by kaangiray26** [comment]
added in [v1.1](https://github.com/kaangiray26/geddit-app/releases/tag/v1.1)

**Comment by PuterPro** [comment]
1. You're most welcome!! It's a _brilliant_ way to handle Reddit's greed. ;)
2.  I bet you're not getting much sleep ... LOL
3. Thanks for the rapid fix
4. Hope this gains enough traction you need a new bank account! If I'm still using it in a week (probable) I'll help towards that. Cheers!
