### ISSUE TITLE
Add to Play Store

### ISSUE THREAD

**Issue by Penknife0915** [kaangiray26/geddit-app#12]
Adding it to the Play Store would offer users a convenient and secure way to access the app.

You may also want to take a look at Accrescent:
https://accrescent.app/
https://accrescent.app/docs/index.html

**Comment by kaangiray26** [comment]
I'll try to add the app to F-Droid but I believe uploading the app to Play Store would raise more problems, so I'm not sure about that right now 😬

**Comment by kaangiray26** [comment]
I'll leave this issue open to attract more possible alternatives and options for the future.

**Comment by kaangiray26** [comment]
> It would be great if every new release on Github could include a SHA-256 checksum, allowing users to verify the integrity of the downloaded app.

This is a great advice, I'll definitely add checksums. I've also updated the first release and added the checksum file.  
Thanks!
