### ISSUE TITLE
Full featured comment trees

### ISSUE THREAD

**Issue by genesysguy** [kaangiray26/geddit-app#17]
Posts only show 15 comments.
Is this a limitation of the rss feed?

**Comment by kaangiray26** [comment]
Hi, no it's not a limitation. I've just not implemented the whole comment tree thing yet. I might add it soon.

**Comment by PDXUser** [comment]
I would love to have more than 15 comments!!!  Please proceed.  I think you could then market the app as a full alternative to Reddit's horrible one!  :)

**Comment by kaangiray26** [comment]
I'm looking into this feature at the moment :+1:

**Comment by genesysguy** [comment]
I still only see roughly 15 comments.  There are sub comments now but still not all of the comments.  Scrolling is also funky bow.
