### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by IzzySoft** [kaangiray26/geddit-app#18]
Can you please take care about versioning? Currently, the APK on each release tag identifies with `versionName: "1.0"` and `versionCode: 1`.

* `versionName` is what shows up in the app. On bug reports you might wish to know what version it is about – this is what will be reported.
* `versionCode` is what Android uses internally to tell versions apart, and to decide if an APK is an update to the installed version. Currently, no update notifications will show up as the code never changes.

You can adjust this [here in your `build.gradle`](https://github.com/kaangiray26/geddit-app/blob/main/android/app/build.gradle#L10). Please do so whenever you make a new release, which then will [show up here](https://apt.izzysoft.de/packages/geddit.buzl.uk/) in my repo – if you wish you can [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link there e.g. from your Readme :smiley:

Thanks in advance!

**Comment by kaangiray26** [comment]
Hi,
thanks for pointing this out, I totally forgot about that! I've now published a new version that has its version numbers updated.

**Comment by IzzySoft** [comment]
> I totally forgot about that!

:hankey: happens :see_no_evil:

> I've now published a new version that has its version numbers updated.

Thanks a lot! Looks good – and should become available with the next sync in my repo then (updates happen daily around 5:30 pm UTC and sync is usually complete around 6 pm UTC). Badge offer still stands :wink:

Speaking about "offer": Would you accept a PR with a starter package for [Fastlane structures](https://gitlab.com/-/snippets/1895688)? That would give you control on how your app is presented.

**Comment by kaangiray26** [comment]
That sounds nice!

I've added a directory for the fastlane structure, is the current status suitable for use? Actually I've been trying to make a release in the fdroid all night. Once the release is merged I'll add both badges for Fdroid and IzzyOnDroid.

Thanks

**Comment by IzzySoft** [comment]
> I've added a directory for the fastlane structure, is the current status suitable for use?

Wow, that looks really good indeed! May I suggest moving the screenshots from `/images/screenshots` to `/fastlane/metadata/android/en-US/images/phoneScreenshots` to complement this? Meanwhile, I've told my updater to fetch what was established now, whenever a new release is being fetched. Once screenshots are there, I'll amend that to the settings.

> Actually I've been trying to make a release in the fdroid all night. Once the release is merged I'll add both badges for Fdroid and IzzyOnDroid.

Wonderful! Usually, once an app reaches F-Droid.org it gets removed from my repo – unless the authors explicitly request to keep it there. If you can achieve [reproducible builds](https://gitlab.com/-/snippets/2544837), that could be done (otherwise it might cause some confusion due to the different signatures; only with reproducible builds, F-Droid would ship the APK signed by you).

Expect includion with F-Droid take at least a few days (if you're lucky, it can be achieved in about a week. But usually it takes a bit more (if issues arise, it can stretch quite a bit). So you might consider adding the badge for my repo now (so interested folks already get the idea), and F-Droid's when it's ready.
