### ISSUE TITLE
Tall images get cropped 

### ISSUE THREAD

**Issue by Nogooduser** [kaangiray26/geddit-app#24]
If an image in a post is taller than the device's display ([example](https://www.reddit.com/r/manga/comments/155s6t2/top_20_most_popular_serialized_manga_series_of/)), geddit will crop it without any way to view the rest of the image (outside of downloading it).

Ideally there should be a way to pan/zoom for larger images.

**Comment by kaangiray26** [comment]
Hi, this will get fixed along with the progress in the md3 design branch.

**Comment by kaangiray26** [comment]
I can confirm now that the image is displayed in full size and therefore I am closing this issue.
