### ISSUE TITLE
Launching browsers internally bypasses their incognito mode

### ISSUE THREAD

**Issue by Penknife0915** [kaangiray26/geddit-app#39]
Currently, when users click on links, the app internally launches the external browser, unintentionally bypassing the browser's incognito mode.

An option that allows users to open the links outside the app by launching their device's default web browser would solve this problem.

**Comment by kaangiray26** [comment]
I've added an option in the settings to enable/disable the in-app browser.

**Comment by kaangiray26** [comment]
The option is now in the latest release and therefore I'm closing this issue. Thanks for the heads-up :)
