### ISSUE TITLE
Material Design & Material You support

### ISSUE THREAD

**Issue by RGBCube** [kaangiray26/geddit-app#5]
Could geddit UI be made to be mYou and MD3?

**Comment by zoroya1** [comment]
@kaangiray26 please consider this request:)

**Comment by kaangiray26** [comment]
@RGBCube @zoroya1 I actually like seeing MD on my android phone but since the code for this app is just basically a web app, I must ask: is there a way to add MD to a web project? I'd be happy if you guys can steer me to the right direction :)

**Comment by RGBCube** [comment]
> @RGBCube @zoroya1 I actually like seeing MD on my android phone but since the code for this app is just basically a web app, I must ask: is there a way to add MD to a web project? I'd be happy if you guys can steer me to the right direction :)

Google does have a material design framework for the web[1] but I don't know how it would use Material You in the app, maybe some CSS patching in startup?

1 - https://github.com/material-components/material-components-web

**Comment by kaangiray26** [comment]
https://github.com/kaangiray26/geddit-app/tree/md3

**Comment by kaangiray26** [comment]
I'm trying to recreate material design components by following the specs and guidelines from the website.

Here's the CSS for the components that I use: https://github.com/kaangiray26/geddit-app/blob/md3/src/assets/md3.css

I'm actually enjoying this 😆

**Comment by kaangiray26** [comment]
A little sneak peek of what will come (take a look at the navigation bar)

![Screen Shot 2023-07-23 at 12 01 30](https://github.com/kaangiray26/geddit-app/assets/11297495/213ef0c6-dcc8-408f-a3c7-7f6dc07dbe0e)

**Comment by kaangiray26** [comment]
Meta issues:
- [x] Navigation bar
- [ ] Top app bar

**Comment by RGBCube** [comment]
> A little sneak peek of what will come (take a look at the navigation bar)
> 
> ![Screen Shot 2023-07-23 at 12 01 30](https://github.com/kaangiray26/geddit-app/assets/11297495/213ef0c6-dcc8-408f-a3c7-7f6dc07dbe0e)
> 

It looks awesome already! keep up the good work

**Comment by kaangiray26** [comment]
I'm closing this one so that we can continue with the other one :)
