### ISSUE TITLE
Material Design 3 problem

### ISSUE THREAD

**Issue by resiehnnes** [kaangiray26/geddit-app#77]
This is how the app looked before version 1.6, and how it looks now. something is messed. I am running Android 10 on Huawei P30 Pro.

![803371cf-96ba-4afa-9194-00b33b9fbfd0](https://github.com/kaangiray26/geddit-app/assets/52158526/22990f1d-5ff0-4d68-9f84-0c94092ed274)

![624e9899-9259-4d64-abbe-254162c49825](https://github.com/kaangiray26/geddit-app/assets/52158526/edf2d005-29e2-4a57-b436-1bb5dec7ef1c)

![d515335f-933b-4e83-91b6-c0ba87671672](https://github.com/kaangiray26/geddit-app/assets/52158526/0f1126cc-43f0-4a5b-a4a1-bc9dbf4341f8)

![02657299-b0c6-48cd-b87e-d4246568a978](https://github.com/kaangiray26/geddit-app/assets/52158526/636b1f35-7a14-45cd-b8a0-8e048414917e)

**Comment by tiritibambix** [comment]
Are you using some kind of adblocker?

I use Pihole and I have the same problem, which is gone when I disable it.

**Comment by Stupefacient** [comment]
It looks your VPN or DNS is blocking Google front leading to your phone default to load which causing the sizing issue.

**Comment by resiehnnes** [comment]
@tiritibambix Yes indeed, removed app from Adguard filtering and problem is gone.
@Stupefacient This is exactly the case, thanks for the details!
